### ISSUE TITLE
Failed to parse error on morph

### ISSUE THREAD

**Issue by otherchirps** [otherchirps/noosa_council#1]
Locally, seems to complete it's run ok.  But on morph.io, is throwing a fatal error (on different DAs), like:

```
Traceback (most recent call last):
  File "scraper.py", line 42, in <module>
    start_url=os.environ.get('MORPH_START_URL', DEFAULT_START_URL)
  File "scraper.py", line 23, in main
    da_info = extract_application_details(application_url)
  File "/app/scraperlib/local_knowledge.py", line 122, in extract_application_details
    raise ValueError("Failed to parse: " + application_url)
ValueError: Failed to parse: https://noosa-eproperty.t1cloud.com/NOOEPRPROD/P1/eTrack/eTrackApplicationDetails.aspx?r=P1.WEBGUEST&f=$P1.ETR.APPDET.VIW&ApplicationId=PC15/0873
```

The planningalerts instance choked on a different application (PC15/0897, versus the PC15/0873 seen here).

**Comment by otherchirps** [comment]
On second run the process completed ok.  Quizzing the api for the DA that it choked on last time shows it's there (though it wasn't listed in the list of newly Saved items... already saved, despite choke?)

Will watch tomorrow's run & see if problem happens again.

**Comment by otherchirps** [comment]
Seems to be behaving now.  Maybe was due to the recent capacity issues that just got resolved... closing.
