### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by otherchirps** [otherchirps/noosa_council#2]
Seeing this on the planningalerts instance:

```
Traceback (most recent call last):
   File "scraper.py", line 42, in <module>
     start_url=os.environ.get('MORPH_START_URL', DEFAULT_START_URL)
   File "scraper.py", line 23, in main
     da_info = extract_application_details(application_url)
   File "/app/scraperlib/local_knowledge.py", line 122, in extract_application_details
     raise ValueError("Failed to parse: " + application_url)
 ValueError : Failed to parse: https://noosa-eproperty.t1cloud.com/NOOEPRPROD/P1/eTrack/eTrackApplicationDetails.aspx?r=P1.WEBGUEST&f=$P1.ETR.APPDET.VIW&ApplicationId=OPW16/0090
```

Need to look at the guilty page and see why the scraper is choking.

**Comment by otherchirps** [comment]
Seems that the noosa council site itself is having problems.  Going manually via their [search interface](https://noosa-eproperty.t1cloud.com/NOOEPRPROD/P1/eTrack/eTrackApplicationSearchResults.aspx?Field=S&Period=TM&r=P1.WEBGUEST&f=$P1.ETR.SEARCH.STM), clicking on any of the individual application links gives:

![screen shot 2016-05-05 at 10 52 53 am](https://cloud.githubusercontent.com/assets/385384/15033631/1edf8194-12b0-11e6-91a9-79f7d9bd1813.png)

**Comment by otherchirps** [comment]
Upstream no longer in use.  Closing.
