### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by otherchirps** [otherchirps/noosa_council#3]
Seeing this on live & test runs:

```
Traceback (most recent call last):
   File "scraper.py", line 42, in <module>
     start_url=os.environ.get('MORPH_START_URL', DEFAULT_START_URL)
   File "scraper.py", line 23, in main
     da_info = extract_application_details(application_url)
   File "/app/scraperlib/local_knowledge.py", line 103, in extract_application_details
     display_name = display_name.strip()
 AttributeError: 'NoneType' object has no attribute 'strip'
```

It's processing several applications before hitting this, so there's something different about a specific application we need to cater for.

**Comment by otherchirps** [comment]
Can see what's going wrong with this one now.

To find the field:value pairs on the application detail page, the scraper extracts all the ``td`` elements of a certain class, and pulls out their text values.

Some applications don't have "plain text" field names though.  Some have document links:

![field_name_as_link](https://cloud.githubusercontent.com/assets/385384/22770898/bd526fbc-eee7-11e6-97ed-607ede0a6365.png)

This gives markup like the following:

![field_name_as_link_markup](https://cloud.githubusercontent.com/assets/385384/22770919/d9f37562-eee7-11e6-8222-d0de70229d4e.png)

Which means here that ``td[1]`` has no text.  In this case, ``td[1]/a`` would have some text for us, but that wasn't what the scraper asked for.

Will simply skip these fields that yield empty names, since we're not after these fields anyway.
